### PR TITLE
Forcing in SAMD support (SAM macro wasn't defined)

### PR DESCRIPTION
**Pull request by malachib**
Passes simple tests with Sparkfun SAMD21 mini breakout

### CODE REVIEW

**Comment by mikaelpatel** [comment]
Lack board to test on therefore this was not included. What validation have you done? Benchmark results?

**Comment by mikaelpatel** [comment]
Not possible to use the same configuration. This MCU has only 32 Kbyte as Teensy 3.1. I can do an update with support but must ask for help with testing.

**Comment by mikaelpatel** [comment]
Please test commit https://github.com/mikaelpatel/Arduino-Scheduler/commit/90d94412d0d4009b8c8cc063cb47f2bf7e4073aa.

**Comment by malachib** [comment]
I will def help with testing when I get back in town!

**Comment by mikaelpatel** [comment]
Thanks!

**Pull request closed without merging**
